for(i=1;i<=100;i++){
    if(i%5!=0){
        if(i%3!=0){
            console.log(i);
        }
        else{
            console.log("Fizz");
        }
        
    }
    else{
        if(i%3!=0){
            console.log("Buzz");
        }
        else{
            console.log("FizzBuzz");
        }
    }
}